[versions]
activity-compose = "1.8.2"
androidx-junit = "1.1.5"
android-gradle-plugin = "8.2.1"
androidx-room-compiler = "2.6.1"
coil-compose = "2.4.0"
coil = "2.4.0"
compose-ratingbar = "1.3.4"
converter-gson = "2.9.0"
core = "11.1.0"
core-ktx = "1.12.0"
compose-bom = "2023.10.01"
core-splashscreen = "1.0.0"
datastore-preferences = "1.0.0"
espresso-core = "3.5.1"
firebase-bom = "32.7.0"
google-hilt = "2.48"
google-gms = "4.4.0"
hilt-android = "2.48"
hilt-android-compiler = "2.47"
hilt-navigation-compose = "1.1.0"
junit = "4.13.2"
jetbrains-kotlin = "1.9.20"
lifecycle-runtime-compose = "2.7.0"
lifecycle-runtime-ktx = "2.7.0"
lifecycle-viewmodel-compose = "2.7.0"
navigation-compose = "2.7.6"
okhttp = "4.11.0"
paging-compose = "3.3.0-alpha02"
paging-runtime-ktx = "3.2.1"
retrofit = "2.9.0"
room-compiler = "2.6.1"
room-ktx = "2.6.1"
room-runtime = "2.6.1"
constraintlayout = "2.1.4"
org-jetbrains-kotlin-jvm = "1.9.20"
javax-inject = "1"
firebase-storage-ktx = "20.3.0"
play-services-auth = "21.0.0"
generativeai = "0.2.2"
palette = "1.0.0"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "core-splashscreen" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore-preferences" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle-runtime-compose" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel-compose" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging-compose" }
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging-runtime-ktx" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room-compiler" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room-ktx" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room-runtime" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
compose-ratingbar = { module = "com.github.a914-gowtham:compose-ratingbar", version.ref = "compose-ratingbar" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converter-gson" }
core = { module = "com.pierfrancescosoffritti.androidyoutubeplayer:core", version.ref = "core" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-auth = { module = "com.google.firebase:firebase-auth-ktx" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
firebase-storage = { module = "com.google.firebase:firebase-storage" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-android" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt-android-compiler" }
junit = { module = "junit:junit", version.ref = "junit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room-compiler" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
javax-inject = { module = "javax.inject:javax.inject", version.ref = "javax-inject" }
firebase-storage-ktx = { group = "com.google.firebase", name = "firebase-storage-ktx", version.ref = "firebase-storage-ktx" }
google-android-gms = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "play-services-auth" }
google-ai-client-generativeai = { group = "com.google.ai.client.generativeai", name = "generativeai", version.ref = "generativeai" }
androidx-compose-material3-windowsize = { group = "androidx.compose.material3", name = "material3-window-size-class" }
androidx-palette = { module = "androidx.palette:palette", version.ref = "palette" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "jetbrains-kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "google-hilt" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-gms" }
androidLibrary = { id = "com.android.library", version.ref = "android-gradle-plugin" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "org-jetbrains-kotlin-jvm" }